export const UPDATE_MATCH_TYPE = 'UPDATE_MATCH_TYPE';
export const TOGGLE_TURN = 'TOGGLE_TURN';
export const UPDATE_SNAPSHOT = 'UPDATE_SNAPSHOT';
export const UPDATE_SELECTED_CODE = 'UPDATE_SELECTED_CODE';
export const COMPUTE_MOVABLE_TILES = 'COMPUTE_MOVABLE_TILES';
